replicaCount: 1

image:
  repository: sensors-data-collector
  tag: dev
  pullPolicy: IfNotPresent

imagePullSecrets: []
serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8083

env:
  HTTP_PORT: "8083"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
