replicaCount: 1

image:
  repository: sensors-data-collector
  tag: dev
  pullPolicy: IfNotPresent

imagePullSecrets: []
serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8083

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: sensors-data-collector.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  HTTP_PORT: "8083"
  LOG_LEVEL: "DEBUG"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
