{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "occupancy-monitor.serviceAccountName" . }}
  labels:
    {{- include "occupancy-monitor.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
