{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sensors-data-collector.serviceAccountName" . }}
  labels:
    {{- include "sensors-data-collector.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
