services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: breathinghouse-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  kafka:
    image: apache/kafka:4.1.0
    container_name: breathinghouse-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,DOCKER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://localhost:9092,DOCKER://breathinghouse-kafka:9093,EXTERNAL://172.21.62.80:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,DOCKER:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@breathinghouse-kafka:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafka-init:
    image: apache/kafka:4.1.0
    depends_on:
      - kafka
    command: >
      sh -c "
        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server breathinghouse-kafka:9093 --list > /dev/null 2>&1;
        do
          sleep 1;
        done;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server breathinghouse-kafka:9093 --create --if-not-exists --topic sensor-data;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server breathinghouse-kafka:9093 --create --if-not-exists --topic event-data;
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server breathinghouse-kafka:9093 --create --if-not-exists --topic status-data;"