server.port=${HTTP_PORT:8083}

# MQTT consumer configuration
mqtt.broker-ip=${MQTT_BROKER_IP:localhost}
mqtt.broker-port=${MQTT_BROKER_PORT:1883}
mqtt.client-id=${MQTT_CLIENT_ID:sensors-data-collector}
mqtt.consumer-topics=${MQTT_CONSUMER_TOPICS:home/+/room,home/+/air,home/+/opening,home/+/presence,home/gateway/status}
mqtt.initial-delay-ms=${MQTT_INITIAL_DELAY_MS:1000}
mqtt.max-delay-ms=${MQTT_MAX_DELAY_MS:60000}
