replicaCount: 1

image:
  repository: environment-monitor
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: nginx
  annotations: {}
  hosts:
    - host: environment-monitor.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  HTTP_PORT: "8080"
  SHUTDOWN_TIMEOUT: 10s
  LOG_LEVEL: info

livenessProbe:
  httpGet:
    path: /live
    port: http
  initialDelaySeconds: 2
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 2
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
