CREATE SCHEMA IF NOT EXISTS environment;
CREATE SCHEMA IF NOT EXISTS occupancy;
CREATE SCHEMA IF NOT EXISTS home_api;

CREATE TABLE IF NOT EXISTS environment.environment_reading (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL,
  device_id TEXT,
  sensor_type TEXT NOT NULL CHECK (sensor_type IN ('ROOM', 'AIR')),
  temperature DOUBLE PRECISION,
  humidity DOUBLE PRECISION,
  co2 DOUBLE PRECISION,
  light DOUBLE PRECISION,
  light_level TEXT,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kafka_topic TEXT,
  kafka_partition INT,
  kafka_offset BIGINT
);

CREATE TABLE IF NOT EXISTS occupancy.occupancy_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL,
  device_id TEXT,
  event_type TEXT NOT NULL CHECK (event_type IN ('PRESENCE', 'OPENING')),
  present BOOLEAN,
  open BOOLEAN,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kafka_topic TEXT,
  kafka_partition INT,
  kafka_offset BIGINT
);

CREATE TABLE IF NOT EXISTS home_api.alert (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule_id TEXT NOT NULL,
  room_id TEXT NOT NULL,
  device_id TEXT,
  severity TEXT NOT NULL,
  status TEXT NOT NULL,
  message TEXT NOT NULL,
  trigger_value TEXT,
  triggered_at TIMESTAMP WITH TIME ZONE NOT NULL,
  resolved_at TIMESTAMP WITH TIME ZONE,
  last_evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  rule_snapshot JSON NOT NULL
);

CREATE TABLE IF NOT EXISTS home_api.alert_state (
  rule_id TEXT NOT NULL,
  room_id TEXT NOT NULL,
  device_key TEXT NOT NULL,
  device_id TEXT,
  condition_active BOOLEAN NOT NULL,
  condition_started_at TIMESTAMP WITH TIME ZONE,
  last_value TEXT,
  rule_fingerprint TEXT NOT NULL,
  last_evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  PRIMARY KEY (rule_id, room_id, device_key)
);

CREATE TABLE IF NOT EXISTS home_api.gateway_heartbeat (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gateway_id TEXT NOT NULL,
  device_id TEXT,
  reported_status TEXT NOT NULL,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  payload JSON NOT NULL,
  kafka_topic TEXT NOT NULL,
  kafka_partition INT NOT NULL,
  kafka_offset BIGINT NOT NULL,
  UNIQUE (kafka_topic, kafka_partition, kafka_offset)
);

CREATE INDEX IF NOT EXISTS gateway_heartbeat_gateway_received_idx
  ON home_api.gateway_heartbeat (gateway_id, received_at DESC, id DESC);
