CREATE SCHEMA IF NOT EXISTS environment;
CREATE SCHEMA IF NOT EXISTS occupancy;

CREATE TABLE IF NOT EXISTS environment.environment_reading (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL,
  device_id TEXT,
  sensor_type TEXT NOT NULL CHECK (sensor_type IN ('ROOM', 'AIR')),
  temperature DOUBLE PRECISION,
  humidity DOUBLE PRECISION,
  co2 DOUBLE PRECISION,
  light DOUBLE PRECISION,
  light_level TEXT,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kafka_topic TEXT,
  kafka_partition INT,
  kafka_offset BIGINT
);

CREATE TABLE IF NOT EXISTS occupancy.occupancy_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT NOT NULL,
  device_id TEXT,
  event_type TEXT NOT NULL CHECK (event_type IN ('PRESENCE', 'OPENING')),
  present BOOLEAN,
  open BOOLEAN,
  observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  received_at TIMESTAMP WITH TIME ZONE NOT NULL,
  ingested_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  kafka_topic TEXT,
  kafka_partition INT,
  kafka_offset BIGINT
);
