{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alert-notifier.serviceAccountName" . }}
  labels:
    {{- include "alert-notifier.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
