name: Cleanup Old Images

on:
  schedule:
    # Runs every day at midnight to check for old images
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean-ghcr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - alert-notifier
          - environment-monitor
          - home-dashboard
          - occupancy-monitor
          - sensors-data-collector
          - charts/alert-notifier
          - charts/environment-monitor
          - charts/home-dashboard
          - charts/occupancy-monitor
          - charts/sensors-data-collector
    steps:
      - name: Delete older package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package }}
          package-type: 'container'
          min-versions-to-keep: 2
          ignore-versions: 'latest'
          delete-only-package-versions: 'true'
          created-before-days: 7
